### ISSUE TITLE
New record indicator when a record is set (RR/IR/IcR)

### ISSUE THREAD

**Issue by trncb** [CubeClubsNZ/app#19]
Please could an icon be added to an individual when a new record is set, similar to the previous website.

For example, in the Skewb final round in the September Kapiti Cubers meetup, there was a Wellington Region record set by Jack. 
(https://cubeclubs.nz/meetups/120/results/cee8bdc9-0451-4b9a-9331-f1b5148433aa)

**Comment by xbjfk** [comment]
Done! Thank you for the issue

For some reason i cant get it to work for new single island records, but I will add that to the todo

**Comment by trncb** [comment]
Fantastic, thank you Reagan.

I see the little icon is appearing on an individual's results page, which is cool, but it's not appearing on the meetup results page?

**Comment by xbjfk** [comment]
Sorry - I didn't upload the site to the server yet.

If you check now, it should be working
