### ISSUE TITLE
Scheduled time for event is not saving correctly

### ISSUE THREAD

**Issue by trncb** [CubeClubsNZ/app#21]
I added a time of 1-1:15pm for 2x2 in the Kapiti Cubers Oct 2023 meetup. After saving it, the time is displayed as 12am-12:15am.
[https://cubeclubs.nz/meetups/121/schedule](https://cubeclubs.nz/meetups/121/schedule)

Then I tried to add a second event at 2pm
![image](https://github.com/CubeClubsNZ/app/assets/25230171/55176e46-fca5-4d82-ba3e-8aa4369121a4)

which saved as 1am. Interestingly, the original 2x2 event _moved_ to 11am.
![image](https://github.com/CubeClubsNZ/app/assets/25230171/cef4040d-79a7-46f3-a7d0-3f01dd38cf69)

I'm wondering if this has something to do with timezone settings somewhere?

**Comment by pdtxie** [comment]
might be an issue with time zones. could be because i'm in the US

**Comment by xbjfk** [comment]
Thank you for the bug report! Fixed.

**Comment by xbjfk** [comment]
I also deleted the current rounds you added for this event manually - since it seems they wouldnt have shown up in the edit schedule UI.
