### ISSUE TITLE
Event results do not display in the same order they were entered

### ISSUE THREAD

**Issue by trncb** [CubeClubsNZ/app#23]
Results entered for an event are not displaying in the same order they were entered, and also appears to be random for every competitor (the order is not consistent)

Eg. Results from the last meetup ([https://cubeclubs.nz/meetups/121/results/2d616f94-de5b-47a2-8cc0-8ef91ee50150](https://cubeclubs.nz/meetups/121/results/2d616f94-de5b-47a2-8cc0-8ef91ee50150))

![image](https://github.com/CubeClubsNZ/app/assets/25230171/a355246d-9922-407b-b88d-b0e82a1c232e)

These were the actual order of the results and how they were entered:
![image](https://github.com/CubeClubsNZ/app/assets/25230171/0ce4a76c-9c84-42d3-aaee-42885fc335ff)

**Comment by xbjfk** [comment]
I will push this change tonight, if it is still present, or present on another page, please file a new issue!
